version: '3'
services:
  go:
    container_name: GoFiber
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      EASY_TOKEN: xxxx
      BEARER: Bearer
      CSV_FILE: ./public/export/result.csv
      CSV_FILE_SEND: ./public/export/result.csv
      DATABASE_TYPE: MySQL
      MYSQL_URI: songvut:1234@tcp(DockerMySQL:3306)/line-town-election?charset=utf8mb4&parseTime=True&loc=Local
    depends_on:
      - "db"

  db:
    image: mysql:8.0
    container_name: DockerMySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: line-town-election
      MYSQL_USER: songvut
      MYSQL_PASSWORD: 1234
      TZ: 'Asia/Bangkok'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-data:
    driver: local